# Based on: https://github.com/isaac-sim/IsaacLab/blob/main/docker/Dockerfile.base
# And: https://github.com/isaac-sim/IsaacLab/blob/main/docker/x11.yaml

x-isaac-volumes: &isaac-volumes
  # Isaac Sim volumes from this page
  # https://docs.omniverse.nvidia.com/app_isaacsim/app_isaacsim/install_faq.html#save-isaac-sim-configs-on-local-disk
  - type: volume
    source: isaac-cache-kit
    target: /isaac-sim/kit/cache
  - type: volume
    source: isaac-cache-ov
    target: /root/.cache/ov
  - type: volume
    source: isaac-cache-pip
    target: /root/.cache/pip
  - type: volume
    source: isaac-cache-gl
    target: /root/.cache/nvidia/GLCache
  - type: volume
    source: isaac-cache-compute
    target: /root/.nv/ComputeCache
  - type: volume
    source: isaac-logs
    target: /root/.nvidia-omniverse/logs
  - type: volume
    source: isaac-carb-logs
    target: /isaac-sim/kit/logs/Kit/Isaac-Sim
  - type: volume
    source: isaac-data
    target: /root/.local/share/ov/data
  - type: volume
    source: isaac-docs
    target: /root/Documents
  - type: bind
    source: ../.isaac-lab-docker-history
    target: /root/.bash_history

  # x11 forwarding
  - type: bind
    source: /tmp/.X11-unix
    target: /tmp/.X11-unix

  # Workspace
  - type: bind
    source: .
    target: /workspace/


x-isaac-environment: &isaac-environment
  - OMNI_KIT_ALLOW_ROOT=1
  - NVIDIA_VISIBLE_DEVICES=all
  - NVIDIA_DRIVER_CAPABILITIES=all
  # x11 forwarding
  - DISPLAY
  - TERM
  - QT_X11_NO_MITSHM=1
  - HEADLESS=0

services:
  isaac-base:
    build:
      context: .
      dockerfile: Dockerfile.isaac
    image: isaac-base
    container_name: isaac-base
    runtime: nvidia
    environment: *isaac-environment
    volumes: *isaac-volumes
    privileged: true
    entrypoint: bash
    stdin_open: true
    tty: true



volumes:
  isaac-cache-kit:
  isaac-cache-ov:
  isaac-cache-pip:
  isaac-cache-gl:
  isaac-cache-compute:
  isaac-logs:
  isaac-carb-logs:
  isaac-data:
  isaac-docs:
